In [2]:
import re
from pathlib import Path

import numpy as np
import pandas as pd
from Bio.PDB import PDBParser
from Bio.SeqUtils import seq1

In [3]:
STANDARD_AA = set("ACDEFGHIKLMNPQRSTVWY")
BACKBONE_ATOMS = {"N", "CA", "C", "O"}
EXCLUDED_ATOM_NAMES = {"OXT"}
ORI_CHAIN_ID = "Z"
VALID_ORI_SOURCES = {"l_chain_all_sidechain", "hotspot_sidechain"}

RFD2_ROOT = Path("/home/junjiechen/1_work/250401-Dpepalign/Benchmark/RFdiffusion2")
CSV_PATH = RFD2_ROOT / "alanine-scan" / "ddg_filtered.csv"
MINIMIZED_DIR = RFD2_ROOT / "minimized"
HOTSPOT_OUT_DIR = RFD2_ROOT / "rfd2_hotspots"
MAPPING_LOG_PATH = HOTSPOT_OUT_DIR / "pose_mapping_debug.csv"

parser = PDBParser(QUIET=True)


def residue_uid(chain_id, residue):
    _, resseq, icode = residue.id
    return (chain_id, int(resseq), (icode or " ").strip())


def residue_is_standard_aa(residue):
    hetflag = residue.id[0]
    if hetflag.strip():
        return False
    try:
        aa = seq1(residue.get_resname())
    except Exception:
        return False
    return aa in STANDARD_AA


def atom_is_excluded(atom):
    atom_name = atom.get_name().strip().upper()
    if atom_name in EXCLUDED_ATOM_NAMES:
        return True
    # Covers H, HA, HB2, HG..., and also 1H/2H/3H naming styles.
    if atom_name.startswith("H") or (len(atom_name) > 1 and atom_name[0].isdigit() and atom_name[1] == "H"):
        return True
    return False


def build_pose_index_map(model):
    """Reproduce pose indexing used in gen_mutfile.ipynb."""
    pose_to_residue = {}
    pose_to_meta = {}
    pose_index = 0
    for chain in model:
        for residue in chain:
            if not residue_is_standard_aa(residue):
                continue
            pose_index += 1
            uid = residue_uid(chain.id, residue)
            pose_to_residue[pose_index] = residue
            pose_to_meta[pose_index] = {
                "chain": chain.id,
                "resseq": uid[1],
                "icode": uid[2],
                "resname3": residue.get_resname().strip(),
                "resname1": seq1(residue.get_resname()),
            }
    return pose_to_residue, pose_to_meta


def parse_mutant_series(mutants):
    """Extract wt_aa and pose_index from strict Mutant format like F110A."""
    clean = mutants.astype(str).str.strip()
    m = clean.str.fullmatch(r"([A-Za-z])(\d+)([A-Za-z])")
    if not m.all():
        bad = clean[~m]
        raise ValueError(f"Mutant解析失败(非法格式):\n{bad.to_string(index=False)}")

    parsed = clean.str.extract(r"^([A-Za-z])(\d+)[A-Za-z]$")
    return parsed[0].str.upper(), parsed[1].astype(int)


def get_backbone_atoms_of_chain(model, chain_id="L"):
    if chain_id not in model:
        raise KeyError(f"Chain {chain_id} not found")
    atoms = []
    for residue in model[chain_id]:
        if not residue_is_standard_aa(residue):
            continue
        for atom in residue:
            atom_name = atom.get_name().strip()
            if atom_name in BACKBONE_ATOMS and not atom_is_excluded(atom):
                atoms.append(atom)
    return atoms


def atom_distance(atom1, atom2):
    return float(np.linalg.norm(atom1.coord - atom2.coord))


def min_distance_to_query_atoms(residue, query_atoms):
    residue_atoms = [atom for atom in residue.get_atoms() if not atom_is_excluded(atom)]
    if not residue_atoms:
        return float("inf")

    min_d = float("inf")
    for atom in residue_atoms:
        d = min(atom_distance(atom, q) for q in query_atoms)
        if d < min_d:
            min_d = d
    return min_d


def sidechain_atoms(residue):
    atoms = []
    for atom in residue.get_atoms():
        atom_name = atom.get_name().strip()
        if atom_name in BACKBONE_ATOMS:
            continue
        if atom_is_excluded(atom):
            continue
        atoms.append(atom)
    return atoms


def get_l_chain_all_sidechain_atoms(model, chain_id="L"):
    if chain_id not in model:
        raise KeyError(f"Chain {chain_id} not found")
    atoms = []
    for residue in model[chain_id]:
        if not residue_is_standard_aa(residue):
            continue
        atoms.extend(sidechain_atoms(residue))
    return atoms


def calculate_centroid_from_atoms(atoms):
    if not atoms:
        raise ValueError("No atoms available for centroid calculation")
    coords = np.array([atom.coord for atom in atoms], dtype=float)
    centroid = coords.mean(axis=0)
    return float(centroid[0]), float(centroid[1]), float(centroid[2])


def build_protein_resname_overrides(neighbor_uids, uid_to_residue):
    """Rename non-L extracted residues as single-letter + serial, e.g., W01, F03."""
    overrides = {}
    for i, uid in enumerate(neighbor_uids, start=1):
        residue = uid_to_residue.get(uid)
        if residue is None:
            continue
        aa1 = seq1(residue.get_resname()).upper()
        if aa1 not in STANDARD_AA:
            aa1 = "X"
        overrides[uid] = f"{aa1}{i:02d}"
    return overrides


def format_pdb_atom_line(atom, serial, record="ATOM", resname_override=None):
    res = atom.get_parent()
    chain = res.get_parent()
    atom_name = atom.get_name().strip()
    altloc = atom.get_altloc() if atom.get_altloc() != " " else " "
    if resname_override is None:
        resname = res.get_resname().strip()[:3]
    else:
        resname = str(resname_override).strip()[:3]
    chain_id = chain.id
    _, resseq, icode = res.id
    x, y, z = atom.coord
    occ = atom.get_occupancy() if atom.get_occupancy() is not None else 1.00
    bfac = atom.get_bfactor() if atom.get_bfactor() is not None else 0.00
    element = (atom.element or atom_name[0]).strip().upper()[:2]
    if len(atom_name) < 4:
        atom_name_fmt = f" {atom_name:<3}"
    else:
        atom_name_fmt = atom_name[:4]
    return (
        f"{record:<6}{serial:>5d} {atom_name_fmt}{altloc:1}"
        f"{resname:>3s} {chain_id:1s}{int(resseq):>4d}{(icode or ' '):1s}   "
        f"{x:>8.3f}{y:>8.3f}{z:>8.3f}{occ:>6.2f}{bfac:>6.2f}          {element:>2s}"
    )


def format_ori_hetatm_line(ori_coord, chain_id=ORI_CHAIN_ID):
    x, y, z = ori_coord
    return (
        f"HETATM{9999:>5d} "
        f"{'ORI':^4s} {'ORI':3s} {chain_id:1s}{1:>4d}"
        f"    "
        f"{x:8.3f}{y:8.3f}{z:8.3f}"
        f"{0.00:6.2f}{0.00:6.2f}      "
        f"{'':4s}{'OR':>2s}"
        f"  "
    )


def safe_file_stem(file_name):
    name = Path(str(file_name)).name
    stem = name[4:] if name.startswith("ddg_") else name
    return re.sub(r"[^A-Za-z0-9_.-]", "_", stem)


def process_one_file(file_name, grp_df, l_chain="L", cutoff=8.0, ori_source="l_chain_all_sidechain"):
    try:
        if ori_source not in VALID_ORI_SOURCES:
            raise ValueError(f"Unsupported ori_source: {ori_source}")

        pdb_stem = safe_file_stem(file_name)
        pdb_path = MINIMIZED_DIR / f"{pdb_stem}.pdb"
        if not pdb_path.exists():
            return {
                "file": file_name,
                "status": "missing_pdb",
                "message": str(pdb_path),
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, []

        structure = parser.get_structure(file_name, str(pdb_path))
        model = structure[0]

        if ORI_CHAIN_ID in {chain.id for chain in model}:
            return {
                "file": file_name,
                "status": "error",
                "message": f"ORI chain conflict: chain {ORI_CHAIN_ID} already exists",
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, []

        wt_series, pose_series = parse_mutant_series(grp_df["Mutant"])
        grp = grp_df.copy()
        grp["wt_aa"] = wt_series.values
        grp["pose_index"] = pose_series.values

        _, pose_to_meta = build_pose_index_map(model)
        mapping_rows = []
        target_uids = []

        for _, row in grp.iterrows():
            pose_idx = int(row["pose_index"])
            wt_aa = row["wt_aa"]
            mut = row["Mutant"]

            meta = pose_to_meta.get(pose_idx)
            if meta is None:
                mapping_rows.append({
                    "File": file_name,
                    "Mutant": mut,
                    "wt_aa": wt_aa,
                    "pose_index": pose_idx,
                    "mapped": False,
                    "reason": "pose_not_found",
                    "mapped_chain": "",
                    "mapped_resseq": np.nan,
                    "mapped_icode": "",
                    "mapped_resname1": "",
                    "wt_match": False,
                })
                continue

            mapped_chain = meta["chain"]
            mapped_resseq = meta["resseq"]
            mapped_icode = meta["icode"]
            mapped_resname1 = meta["resname1"]
            wt_match = (wt_aa == mapped_resname1)

            reason = "ok"
            if mapped_chain != l_chain:
                reason = "not_in_L_chain"
            elif not wt_match:
                reason = "wt_mismatch"
            else:
                target_uids.append((mapped_chain, mapped_resseq, mapped_icode))

            mapping_rows.append({
                "File": file_name,
                "Mutant": mut,
                "wt_aa": wt_aa,
                "pose_index": pose_idx,
                "mapped": True,
                "reason": reason,
                "mapped_chain": mapped_chain,
                "mapped_resseq": mapped_resseq,
                "mapped_icode": mapped_icode,
                "mapped_resname1": mapped_resname1,
                "wt_match": wt_match,
            })

        target_uids = sorted(set(target_uids), key=lambda x: (x[0], x[1], x[2]))
        if not target_uids:
            return {
                "file": file_name,
                "status": "no_valid_L_targets",
                "message": "No valid L-chain targets after pose mapping",
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, mapping_rows

        backbone_atoms = get_backbone_atoms_of_chain(model, chain_id=l_chain)
        if not backbone_atoms:
            return {
                "file": file_name,
                "status": "no_L_backbone",
                "message": "L chain has no standard backbone atoms",
                "output_pdb": "",
                "n_l_targets": len(target_uids),
                "n_neighbors": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, mapping_rows

        uid_to_residue = {
            residue_uid(chain.id, residue): residue
            for chain in model
            for residue in chain
            if residue_is_standard_aa(residue)
        }

        neighbor_uids = []
        for chain in model:
            if chain.id == l_chain:
                continue
            for residue in chain:
                if not residue_is_standard_aa(residue):
                    continue
                dmin = min_distance_to_query_atoms(residue, backbone_atoms)
                if dmin < cutoff:
                    neighbor_uids.append((chain.id, residue.id[1], (residue.id[2] or " ").strip()))

        neighbor_uids = sorted(set(neighbor_uids), key=lambda x: (x[0], x[1], x[2]))

        if ori_source == "l_chain_all_sidechain":
            ori_atoms = get_l_chain_all_sidechain_atoms(model, chain_id=l_chain)
        else:
            ori_atoms = []
            for uid in target_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                ori_atoms.extend(sidechain_atoms(res))
        ori_coord = calculate_centroid_from_atoms(ori_atoms)

        protein_resname_overrides = build_protein_resname_overrides(neighbor_uids, uid_to_residue)

        HOTSPOT_OUT_DIR.mkdir(parents=True, exist_ok=True)
        out_path = HOTSPOT_OUT_DIR / f"{Path(str(file_name)).name}_hotspot.pdb"

        serial = 1
        written = 0
        with open(out_path, "w") as f:
            # Keep original residue names for L-chain hotspot residues.
            for uid in target_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                for atom in sidechain_atoms(res):
                    f.write(format_pdb_atom_line(atom, serial, record="ATOM") + "\n")
                    serial += 1
                    written += 1

            # Rename extracted protein-chain residues as W01/F03/A03...
            for uid in neighbor_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                resname_override = protein_resname_overrides.get(uid)
                for atom in sidechain_atoms(res):
                    f.write(
                        format_pdb_atom_line(
                            atom, serial, record="ATOM", resname_override=resname_override
                        ) + "\n"
                    )
                    serial += 1
                    written += 1

            f.write(format_ori_hetatm_line(ori_coord, chain_id=ORI_CHAIN_ID) + "\n")
            f.write("END\n")

        status = "ok" if written > 0 else "empty_hotspot"
        message = "" if written > 0 else "No sidechain atoms written"
        return {
            "file": file_name,
            "status": status,
            "message": message,
            "output_pdb": str(out_path),
            "n_l_targets": len(target_uids),
            "n_neighbors": len(neighbor_uids),
            "n_written_atoms": written,
            "ori_chain": ORI_CHAIN_ID,
            "ori_source": ori_source,
            "ori_x": ori_coord[0],
            "ori_y": ori_coord[1],
            "ori_z": ori_coord[2],
        }, mapping_rows
    except Exception as exc:
        return {
            "file": file_name,
            "status": "error",
            "message": f"{type(exc).__name__}: {exc}",
            "output_pdb": "",
            "n_l_targets": 0,
            "n_neighbors": 0,
            "n_written_atoms": 0,
            "ori_chain": "",
            "ori_source": ori_source,
            "ori_x": np.nan,
            "ori_y": np.nan,
            "ori_z": np.nan,
        }, []


def validate_input_df(df):
    required = {"File", "Mutant"}
    missing = sorted(required.difference(df.columns))
    if missing:
        raise ValueError(f"CSV缺少必要列: {missing}")

    mask_valid = df["File"].notna() & df["Mutant"].notna()
    if not mask_valid.all():
        bad_n = int((~mask_valid).sum())
        print(f"警告: 跳过 {bad_n} 行 File/Mutant 缺失的数据")
        df = df.loc[mask_valid].copy()

    df["File"] = df["File"].astype(str).str.strip()
    df["Mutant"] = df["Mutant"].astype(str).str.strip()

    mask_nonempty = (df["File"] != "") & (df["Mutant"] != "")
    if not mask_nonempty.all():
        bad_n = int((~mask_nonempty).sum())
        print(f"警告: 跳过 {bad_n} 行 File/Mutant 为空字符串的数据")
        df = df.loc[mask_nonempty].copy()

    return df


def run_stage1_stage2_debug(
    csv_path=CSV_PATH,
    smoke_n=3,
    run_full=False,
    l_chain="L",
    cutoff=8.0,
    ori_source="l_chain_all_sidechain",
    write_mapping_log=True,
):
    if ori_source not in VALID_ORI_SOURCES:
        raise ValueError(
            f"ori_source必须是 {sorted(VALID_ORI_SOURCES)} 之一, 当前: {ori_source}"
        )

    df_raw = pd.read_csv(csv_path)
    df = validate_input_df(df_raw)

    grouped = list(df.groupby("File", sort=True))
    selected = grouped if run_full else grouped[:smoke_n]

    print(f"Total files in CSV: {len(grouped)}")
    print(f"Files to process now: {len(selected)}")
    print(f"ORI source: {ori_source}")

    summaries = []
    mapping_all = []
    for file_name, grp in selected:
        summary, mapping_rows = process_one_file(
            file_name, grp, l_chain=l_chain, cutoff=cutoff, ori_source=ori_source
        )
        summaries.append(summary)
        mapping_all.extend(mapping_rows)

        msg = (
            f"[{summary['status']}] {file_name} | "
            f"L_targets={summary['n_l_targets']} neighbors={summary['n_neighbors']} atoms={summary['n_written_atoms']}"
        )
        if summary["ori_chain"]:
            msg += f" ORI=({summary['ori_x']:.3f}, {summary['ori_y']:.3f}, {summary['ori_z']:.3f})"
        print(msg)

    df_summary = pd.DataFrame(summaries)
    df_mapping = pd.DataFrame(mapping_all)

    if write_mapping_log and not df_mapping.empty:
        HOTSPOT_OUT_DIR.mkdir(parents=True, exist_ok=True)
        df_mapping.to_csv(MAPPING_LOG_PATH, index=False)
        print(f"\nMapping log saved: {MAPPING_LOG_PATH}")

    return df_summary, df_mapping


# Debug run: set run_full=True when smoke test passes
df_debug_summary, df_debug_mapping = run_stage1_stage2_debug(
    smoke_n=3,
    run_full=True,
    l_chain="L",
    cutoff=8.0,
    ori_source="l_chain_all_sidechain",
    write_mapping_log=True,
 )

display(df_debug_summary)
display(df_debug_mapping.head(20))

Total files in CSV: 148
Files to process now: 148
ORI source: l_chain_all_sidechain
[ok] ddg_1ddv_0012 | L_targets=1 neighbors=19 atoms=90 ORI=(12.254, 18.412, -0.591)
[ok] ddg_1eg4_0003 | L_targets=2 neighbors=25 atoms=124 ORI=(53.750, 16.599, 35.935)
[ok] ddg_1f47_0001 | L_targets=6 neighbors=19 atoms=103 ORI=(9.338, 11.238, 14.377)
[ok] ddg_1f8h_0003 | L_targets=2 neighbors=21 atoms=95 ORI=(3.895, -0.621, -1.155)
[ok] ddg_1j2x_0001 | L_targets=6 neighbors=21 atoms=110 ORI=(-0.946, -2.193, 9.972)
[ok] ddg_1jd5_0001 | L_targets=3 neighbors=30 atoms=146 ORI=(-0.708, 47.139, 12.938)
[ok] ddg_1jq8_0001 | L_targets=2 neighbors=31 atoms=140 ORI=(13.131, 21.543, 42.654)
[ok] ddg_1jw6_0019 | L_targets=2 neighbors=19 atoms=94 ORI=(12.546, 31.709, 25.323)
[ok] ddg_1l2z_0001 | L_targets=1 neighbors=17 atoms=98 ORI=(12.182, 0.460, 1.292)
[ok] ddg_1lb6_0004 | L_targets=3 neighbors=26 atoms=131 ORI=(12.313, 23.066, 10.739)
[ok] ddg_1mv0_0001 | L_targets=3 neighbors=30 atoms=153 ORI=(-0.969, -11.447, -14.319)
[ok] ddg_1nrl_0016 | L_targets=7 neighbors=21 atoms=116 ORI=(1.690, 12.045, 18.573)
[ok] ddg_1nvq_0018 | L_targets=2 neighbors=24 atoms=121 ORI=(13.931, 4.008, 32.446)
[ok] ddg_1o0p_0001 | L_targets=6 neighbors=21 atoms=125 ORI=(9.415, -3.344, 7.092)
[ok] ddg_1p7v_0014 | L_targets=1 neighbors=44 atoms=145 ORI=(48.306, 44.852, 39.380)
[ok] ddg_1r17_0004 | L_targets=3 neighbors=63 atoms=268 ORI=(51.203, 13.274, 90.894)
[ok] ddg_1rxz_0001 | L_targets=5 neighbors=30 atoms=151 ORI=(78.673, 26.314, 14.538)
[ok] ddg_1t74_0006 | L_targets=4 neighbors=16 atoms=96 ORI=(38.232, -24.365, 54.164)
[ok] ddg_1v1t_0009 | L_targets=3 neighbors=26 atoms=105 ORI=(8.227, -19.195, 40.319)
[ok] ddg_1w80_0013 | L_targets=3 neighbors=21 atoms=103 ORI=(25.371, -15.212, -5.049)
[ok] ddg_1yfn_0001 | L_targets=7 neighbors=34 atoms=174 ORI=(30.788, -18.168, 7.287)
[ok] ddg_1ywi_0001 | L_targets=1 neighbors=13 atoms=70 ORI=(1.266, 7.602, 0.415)
[ok] ddg_1ywo_0001 | L_targets=1 neighbors=15 atoms=81 ORI=(19.491, 2.467, 25.868)
[ok] ddg_1yy6_0001 | L_targets=1 neighbors=25 atoms=118 ORI=(34.731, -15.809, -8.388)
[ok] ddg_2aq9_0005 | L_targets=3 neighbors=21 atoms=95 ORI=(51.353, 71.420, 65.326)
[ok] ddg_2c3i_0007 | L_targets=3 neighbors=26 atoms=131 ORI=(21.389, 59.438, -12.912)
[ok] ddg_2cch_0010 | L_targets=6 neighbors=29 atoms=169 ORI=(4.982, 14.459, 49.789)
[ok] ddg_2cny_0001 | L_targets=9 neighbors=53 atoms=235 ORI=(30.905, -13.634, 45.015)
[ok] ddg_2e4h_0001 | L_targets=2 neighbors=32 atoms=122 ORI=(-0.313, 3.696, 15.226)
[ok] ddg_2fgr_0005 | L_targets=1 neighbors=13 atoms=57 ORI=(4.479, 58.568, 21.550)
[ok] ddg_2fka_0001 | L_targets=4 neighbors=19 atoms=87 ORI=(42.681, -85.665, -76.304)
[ok] ddg_2hpl_0002 | L_targets=2 neighbors=20 atoms=98 ORI=(49.315, 51.511, 21.337)
[ok] ddg_2ht9_0012 | L_targets=5 neighbors=9 atoms=69 ORI=(-24.072, 56.019, -1.260)
[ok] ddg_2i94_0008 | L_targets=4 neighbors=32 atoms=174 ORI=(4.689, 13.958, -44.329)
[ok] ddg_2ivz_0009 | L_targets=3 neighbors=38 atoms=175 ORI=(16.917, 16.822, 57.636)
[ok] ddg_2jnw_0001 | L_targets=2 neighbors=28 atoms=142 ORI=(-12.514, 7.721, -12.234)
[ok] ddg_2jqk_0001 | L_targets=2 neighbors=18 atoms=84 ORI=(8.369, -4.466, 5.036)
[ok] ddg_2ka9_0008 | L_targets=3 neighbors=26 atoms=97 ORI=(-14.313, -14.215, 16.448)
[ok] ddg_2kbr_0001 | L_targets=6 neighbors=26 atoms=155 ORI=(-9.295, 0.207, 6.375)
[ok] ddg_2ke1_0001 | L_targets=6 neighbors=30 atoms=146 ORI=(11.288, -0.337, 2.138)
[ok] ddg_2khh_0001 | L_targets=4 neighbors=24 atoms=113 ORI=(-11.340, -44.716, 14.315)
[ok] ddg_2koh_0003 | L_targets=4 neighbors=33 atoms=121 ORI=(0.980, -4.739, 20.857)
[ok] ddg_2las_0006 | L_targets=3 neighbors=20 atoms=106 ORI=(6.920, 7.371, 3.767)
[ok] ddg_2lsi_0002 | L_targets=6 neighbors=19 atoms=114 ORI=(14.102, 6.773, 0.548)
[ok] ddg_2m0v_0001 | L_targets=2 neighbors=28 atoms=115 ORI=(2.609, 27.053, 4.432)
[ok] ddg_2nnu_0016 | L_targets=7 neighbors=19 atoms=117 ORI=(32.863, 6.075, 30.385)
[ok] ddg_2o9v_0001 | L_targets=1 neighbors=17 atoms=87 ORI=(26.688, -5.685, -16.188)
[ok] ddg_2p1o_0010 | L_targets=3 neighbors=27 atoms=143 ORI=(14.033, -102.927, -28.981)
[ok] ddg_2qos_0017 | L_targets=5 neighbors=44 atoms=221 ORI=(35.729, 35.070, 50.765)
[ok] ddg_2r7g_0020 | L_targets=6 neighbors=29 atoms=158 ORI=(-6.336, -4.774, 14.363)
[ok] ddg_2rol_0001 | L_targets=2 neighbors=17 atoms=92 ORI=(19.276, 21.231, 11.657)
[ok] ddg_2vzg_0004 | L_targets=6 neighbors=19 atoms=108 ORI=(-18.773, -12.690, 18.348)
[ok] ddg_2xcb_0019 | L_targets=3 neighbors=28 atoms=154 ORI=(-15.377, 37.740, -14.658)
[ok] ddg_2xpn_0005 | L_targets=5 neighbors=29 atoms=142 ORI=(-20.867, 23.512, -2.301)
[ok] ddg_2xrw_0003 | L_targets=5 neighbors=21 atoms=120 ORI=(-9.887, 4.227, 24.532)
[ok] ddg_2ymt_0001 | L_targets=3 neighbors=19 atoms=101 ORI=(-11.119, 6.457, 10.918)
[ok] ddg_3agy_0002 | L_targets=1 neighbors=22 atoms=99 ORI=(3.392, 5.961, 93.493)
[ok] ddg_3bej_0005 | L_targets=5 neighbors=19 atoms=111 ORI=(28.633, 9.184, 0.526)
[ok] ddg_3bqo_0001 | L_targets=8 neighbors=38 atoms=210 ORI=(46.848, 24.427, -18.766)
[ok] ddg_3emh_0003 | L_targets=2 neighbors=32 atoms=132 ORI=(-15.299, -29.422, -5.533)
[ok] ddg_3emw_0013 | L_targets=4 neighbors=20 atoms=99 ORI=(11.078, 30.419, 61.113)
[ok] ddg_3et3_0010 | L_targets=8 neighbors=25 atoms=136 ORI=(52.299, 29.313, 78.550)
[ok] ddg_3fp2_0003 | L_targets=3 neighbors=26 atoms=113 ORI=(-1.765, 20.343, 53.833)
[ok] ddg_3g2s_0001 | L_targets=5 neighbors=24 atoms=125 ORI=(15.181, 3.133, -37.543)
[ok] ddg_3h1z_0013 | L_targets=6 neighbors=29 atoms=155 ORI=(-16.856, -9.509, -40.754)
[ok] ddg_3i5r_0001 | L_targets=3 neighbors=13 atoms=79 ORI=(2.332, 25.221, 18.405)
[ok] ddg_3pe4_0009 | L_targets=3 neighbors=48 atoms=212 ORI=(-12.494, 29.760, 4.742)
[ok] ddg_3plu_0006 | L_targets=6 neighbors=16 atoms=96 ORI=(3.691, -14.692, -4.486)
[ok] ddg_3r42_0018 | L_targets=2 neighbors=20 atoms=99 ORI=(7.259, 15.868, -5.873)
[ok] ddg_3s9c_0004 | L_targets=5 neighbors=35 atoms=150 ORI=(-3.040, 44.360, 3.321)
[ok] ddg_3shb_0006 | L_targets=2 neighbors=21 atoms=95 ORI=(-12.768, 9.962, 13.076)
[ok] ddg_3tiw_0001 | L_targets=5 neighbors=21 atoms=117 ORI=(14.255, -8.348, -20.442)
[ok] ddg_3v2o_0013 | L_targets=2 neighbors=28 atoms=120 ORI=(-4.393, 3.736, 1.649)
[ok] ddg_4a2a_0013 | L_targets=7 neighbors=22 atoms=131 ORI=(-21.144, -7.047, 61.549)
[ok] ddg_4c5a_0012 | L_targets=4 neighbors=10 atoms=64 ORI=(-7.873, 35.880, 33.563)
[ok] ddg_4dg3_0002 | L_targets=6 neighbors=43 atoms=230 ORI=(-14.559, -1.036, 8.962)
[ok] ddg_4ep2_0009 | L_targets=3 neighbors=56 atoms=195 ORI=(20.663, 31.499, 12.939)
[ok] ddg_4fii_0001 | L_targets=4 neighbors=27 atoms=135 ORI=(23.431, -22.862, -4.762)
[ok] ddg_4gq6_0004 | L_targets=3 neighbors=48 atoms=216 ORI=(-8.292, 14.754, 6.888)
[ok] ddg_4hdq_0008 | L_targets=4 neighbors=29 atoms=158 ORI=(29.303, 25.092, 16.964)
[ok] ddg_4hom_0010 | L_targets=5 neighbors=74 atoms=347 ORI=(18.097, 20.152, 60.247)
[ok] ddg_4iga_0001 | L_targets=9 neighbors=21 atoms=117 ORI=(10.624, -28.488, -0.347)
[ok] ddg_4j2c_0001 | L_targets=7 neighbors=22 atoms=134 ORI=(-7.351, 16.974, 20.616)
[ok] ddg_4j8b_0010 | L_targets=5 neighbors=22 atoms=137 ORI=(-31.458, -20.093, 8.222)
[ok] ddg_4lk9_0013 | L_targets=4 neighbors=34 atoms=160 ORI=(8.188, 29.581, 29.511)
[ok] ddg_4lzf_0006 | L_targets=2 neighbors=23 atoms=116 ORI=(5.826, 10.446, -6.829)
[ok] ddg_4m5s_0013 | L_targets=3 neighbors=24 atoms=94 ORI=(10.101, 12.186, 20.033)
[ok] ddg_4mvi_0002 | L_targets=7 neighbors=55 atoms=264 ORI=(-27.015, -1.202, -2.615)
[ok] ddg_4nuu_0006 | L_targets=6 neighbors=24 atoms=139 ORI=(47.166, -44.753, 95.481)
[ok] ddg_4nxr_0008 | L_targets=5 neighbors=29 atoms=147 ORI=(1.253, 12.248, 3.030)
[ok] ddg_4ny3_0016 | L_targets=3 neighbors=18 atoms=94 ORI=(16.201, 5.509, 13.677)
[ok] ddg_4odk_0006 | L_targets=2 neighbors=21 atoms=101 ORI=(-9.147, 11.325, 9.257)
[ok] ddg_4ouc_0018 | L_targets=3 neighbors=34 atoms=163 ORI=(35.645, 54.144, 9.758)
[ok] ddg_4oyk_0002 | L_targets=4 neighbors=24 atoms=142 ORI=(7.651, -6.600, -0.307)
[ok] ddg_4pd1_0009 | L_targets=4 neighbors=29 atoms=143 ORI=(-30.100, -10.447, 8.352)
[ok] ddg_4pge_0001 | L_targets=3 neighbors=58 atoms=300 ORI=(57.451, 25.504, -5.846)
[ok] ddg_4qbr_0001 | L_targets=3 neighbors=33 atoms=143 ORI=(26.399, -32.638, 9.742)
[ok] ddg_4r5i_0008 | L_targets=3 neighbors=33 atoms=132 ORI=(-18.681, -22.112, -29.775)
[ok] ddg_4txr_0001 | L_targets=6 neighbors=19 atoms=118 ORI=(4.192, -14.084, -2.154)
[ok] ddg_4u0c_0001 | L_targets=2 neighbors=23 atoms=94 ORI=(-15.772, 75.748, 1.327)
[ok] ddg_4uqy_0001 | L_targets=7 neighbors=36 atoms=177 ORI=(14.261, -18.704, -33.635)
[ok] ddg_4x2h_0011 | L_targets=2 neighbors=30 atoms=116 ORI=(-76.915, 210.200, 82.037)
[ok] ddg_4x3o_0007 | L_targets=1 neighbors=27 atoms=127 ORI=(8.328, -3.712, 7.837)
[ok] ddg_4xc2_0001 | L_targets=5 neighbors=33 atoms=185 ORI=(16.280, 4.171, -0.331)
[ok] ddg_4xek_0003 | L_targets=6 neighbors=23 atoms=115 ORI=(-23.859, -1.002, 3.081)
[ok] ddg_4z2o_0018 | L_targets=4 neighbors=28 atoms=108 ORI=(-6.343, 3.498, -5.355)
[ok] ddg_5bs2_0004 | L_targets=4 neighbors=13 atoms=83 ORI=(-14.163, 14.731, 0.787)
[ok] ddg_5crw_0003 | L_targets=2 neighbors=25 atoms=96 ORI=(5.450, -5.805, 6.366)
[ok] ddg_5d94_0004 | L_targets=6 neighbors=31 atoms=176 ORI=(14.939, 1.924, 16.790)
[ok] ddg_5dai_0003 | L_targets=6 neighbors=25 atoms=133 ORI=(5.487, 36.308, -0.050)
[ok] ddg_5e33_0004 | L_targets=3 neighbors=47 atoms=231 ORI=(138.196, -21.905, 85.176)
[ok] ddg_5efi_0017 | L_targets=5 neighbors=36 atoms=168 ORI=(32.581, -5.340, 42.908)
[ok] ddg_5ei3_0001 | L_targets=7 neighbors=25 atoms=149 ORI=(1.161, -13.627, -35.958)
[ok] ddg_5fml_0008 | L_targets=8 neighbors=29 atoms=158 ORI=(50.641, 20.792, 38.941)
[ok] ddg_5fpx_0011 | L_targets=3 neighbors=37 atoms=162 ORI=(17.810, 0.412, -4.327)
[ok] ddg_5fv6_0010 | L_targets=2 neighbors=15 atoms=71 ORI=(12.026, 69.178, 3.192)
[ok] ddg_5ggp_0009 | L_targets=1 neighbors=9 atoms=57 ORI=(50.832, 2.997, 12.545)
[ok] ddg_5gu4_0003 | L_targets=3 neighbors=20 atoms=100 ORI=(-14.516, 7.498, 22.064)
[ok] ddg_5huw_0002 | L_targets=2 neighbors=39 atoms=172 ORI=(-2.465, 5.914, -8.107)
[ok] ddg_5i7z_0002 | L_targets=4 neighbors=27 atoms=127 ORI=(17.964, 32.396, -2.848)
[ok] ddg_5j3q_0014 | L_targets=4 neighbors=28 atoms=162 ORI=(-13.536, -20.433, 2.718)
[ok] ddg_5lyn_0001 | L_targets=3 neighbors=31 atoms=139 ORI=(4.931, 6.368, -34.683)
[ok] ddg_5m5r_0014 | L_targets=4 neighbors=29 atoms=122 ORI=(-14.038, -0.605, -15.405)
[ok] ddg_5n22_0001 | L_targets=4 neighbors=29 atoms=143 ORI=(79.853, 41.877, 50.836)
[ok] ddg_5n85_0006 | L_targets=6 neighbors=25 atoms=138 ORI=(5.664, 12.991, -2.696)
[ok] ddg_5njc_0015 | L_targets=1 neighbors=38 atoms=144 ORI=(30.413, 63.947, 50.787)
[ok] ddg_5nqv_0006 | L_targets=3 neighbors=32 atoms=157 ORI=(-30.529, -42.983, 45.386)
[ok] ddg_5oj5_0004 | L_targets=2 neighbors=14 atoms=70 ORI=(27.634, 4.816, -45.172)
[ok] ddg_5onp_0001 | L_targets=2 neighbors=31 atoms=154 ORI=(9.396, 40.641, -2.361)
[ok] ddg_5t0k_0001 | L_targets=3 neighbors=39 atoms=205 ORI=(-71.377, -12.934, 13.010)
[ok] ddg_5tgi_0013 | L_targets=7 neighbors=26 atoms=145 ORI=(4.898, 27.747, -16.944)
[ok] ddg_5v3r_0007 | L_targets=4 neighbors=23 atoms=113 ORI=(30.634, 40.377, 1.803)
[ok] ddg_5wfv_0011 | L_targets=3 neighbors=37 atoms=155 ORI=(-43.855, -9.791, 64.710)
[ok] ddg_5wyi_0011 | L_targets=3 neighbors=16 atoms=93 ORI=(76.117, 3.158, -26.639)
[ok] ddg_5xhz_0001 | L_targets=4 neighbors=19 atoms=113 ORI=(-15.241, 0.830, -1.243)
[ok] ddg_5xxq_0019 | L_targets=6 neighbors=26 atoms=149 ORI=(83.351, 26.319, 232.574)
[ok] ddg_5yay_0001 | L_targets=8 neighbors=42 atoms=190 ORI=(12.904, -10.191, 25.629)
[ok] ddg_6b27_0004 | L_targets=2 neighbors=21 atoms=124 ORI=(15.939, 49.798, 22.106)
[ok] ddg_6co4_0017 | L_targets=2 neighbors=32 atoms=149 ORI=(49.451, -4.948, 8.587)
[ok] ddg_6dei_0014 | L_targets=6 neighbors=25 atoms=145 ORI=(0.914, -3.247, 27.310)
[ok] ddg_6e5x_0012 | L_targets=2 neighbors=25 atoms=114 ORI=(9.234, 2.669, 15.816)
[ok] ddg_6ej7_0007 | L_targets=1 neighbors=42 atoms=190 ORI=(-0.371, 21.433, 72.865)
[ok] ddg_6f0w_0007 | L_targets=6 neighbors=43 atoms=222 ORI=(-13.836, 6.231, -14.360)
[ok] ddg_6f0y_0011 | L_targets=5 neighbors=24 atoms=120 ORI=(-10.440, -6.355, -9.018)
[ok] ddg_6f6d_0002 | L_targets=6 neighbors=68 atoms=302 ORI=(96.271, -19.332, 22.407)
[ok] ddg_6fbk_0001 | L_targets=5 neighbors=18 atoms=107 ORI=(37.879, 33.149, 4.399)
[ok] ddg_6g5g_0004 | L_targets=6 neighbors=27 atoms=165 ORI=(20.902, -4.031, 9.426)
[ok] ddg_6h7b_0001 | L_targets=5 neighbors=26 atoms=131 ORI=(6.286, -32.448, -7.268)

Mapping log saved: /home/junjiechen/1_work/250401-Dpepalign/Benchmark/RFdiffusion2/rfd2_hotspots/pose_mapping_debug.csv

,file,status,message,output_pdb,n_l_targets,n_neighbors,n_written_atoms,ori_chain,ori_source,ori_x,ori_y,ori_z
0,ddg_1ddv_0012,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,1,19,90,Z,l_chain_all_sidechain,12.253952,18.412381,-0.591190
1,ddg_1eg4_0003,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,2,25,124,Z,l_chain_all_sidechain,53.749833,16.598593,35.934945
2,ddg_1f47_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,19,103,Z,l_chain_all_sidechain,9.338446,11.238014,14.376946
3,ddg_1f8h_0003,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,2,21,95,Z,l_chain_all_sidechain,3.895462,-0.620769,-1.154577
4,ddg_1j2x_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,21,110,Z,l_chain_all_sidechain,-0.945857,-2.192730,9.971873
...,...,...,...,...,...,...,...,...,...,...,...,...
143,ddg_6f0y_0011,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,24,120,Z,l_chain_all_sidechain,-10.440464,-6.354768,-9.017911
144,ddg_6f6d_0002,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,68,302,Z,l_chain_all_sidechain,96.270732,-19.331857,22.406536
145,ddg_6fbk_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,18,107,Z,l_chain_all_sidechain,37.878873,33.148841,4.399222
146,ddg_6g5g_0004,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,27,165,Z,l_chain_all_sidechain,20.902349,-4.031205,9.425940
147,ddg_6h7b_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,26,131,Z,l_chain_all_sidechain,6.285840,-32.448020,-7.268360

,File,Mutant,wt_aa,pose_index,mapped,reason,mapped_chain,mapped_resseq,mapped_icode,mapped_resname1,wt_match
0,ddg_1ddv_0012,F110A,F,110,True,ok,L,1006,,F,True
1,ddg_1eg4_0003,Y271A,Y,271,True,ok,L,12,,Y,True
2,ddg_1eg4_0003,R266A,R,266,True,ok,L,7,,R,True
3,ddg_1f47_0001,F155A,F,155,True,ok,L,11,,F,True
4,ddg_1f47_0001,Y149A,Y,149,True,ok,L,5,,Y,True
5,ddg_1f47_0001,L156A,L,156,True,ok,L,12,,L,True
6,ddg_1f47_0001,I152A,I,152,True,ok,L,8,,I,True
7,ddg_1f47_0001,L150A,L,150,True,ok,L,6,,L,True
8,ddg_1f47_0001,D148A,D,148,True,ok,L,4,,D,True
9,ddg_1f8h_0003,F100A,F,100,True,ok,L,111,,F,True
10,ddg_1f8h_0003,R101A,R,101,True,ok,L,112,,R,True
11,ddg_1j2x_0001,L80A,L,80,True,ok,L,953,,L,True
12,ddg_1j2x_0001,L84A,L,84,True,ok,L,957,,L,True
13,ddg_1j2x_0001,M76A,M,76,True,ok,L,949,,M,True
14,ddg_1j2x_0001,D74A,D,74,True,ok,L,947,,D,True
15,ddg_1j2x_0001,L87A,L,87,True,ok,L,960,,L,True
16,ddg_1j2x_0001,M88A,M,88,True,ok,L,961,,M,True
17,ddg_1jd5_0001,Y109A,Y,109,True,ok,L,4,,Y,True
18,ddg_1jd5_0001,I111A,I,111,True,ok,L,6,,I,True
19,ddg_1jd5_0001,F110A,F,110,True,ok,L,5,,F,True

In [4]:
def residue_all_atoms(residue):
    """Return all residue atoms except excluded atoms (H/OXT)."""
    atoms = []
    for atom in residue.get_atoms():
        if atom_is_excluded(atom):
            continue
        atoms.append(atom)
    return atoms


def build_chain_position_index(model):
    """Map standard-AA residue uid to its sequential position within each chain."""
    chain_position_index = {}
    for chain in model:
        pos = 0
        for residue in chain:
            if not residue_is_standard_aa(residue):
                continue
            pos += 1
            chain_position_index[residue_uid(chain.id, residue)] = pos
    return chain_position_index


def split_continuous_neighbor_fragments(neighbor_uids, chain_position_index):
    """Split neighbor residues into continuous fragments using chain-local order."""
    if not neighbor_uids:
        return []

    fragments = []
    current = [neighbor_uids[0]]

    for uid in neighbor_uids[1:]:
        prev = current[-1]
        same_chain = uid[0] == prev[0]
        prev_pos = chain_position_index.get(prev)
        curr_pos = chain_position_index.get(uid)
        if same_chain and prev_pos is not None and curr_pos is not None and curr_pos == prev_pos + 1:
            current.append(uid)
        else:
            fragments.append(current)
            current = [uid]

    fragments.append(current)
    return fragments


def build_protein_resname_overrides(neighbor_uids, uid_to_residue, chain_position_index):
    """
    Naming rule:
    - Continuous fragment (len >= 2): all residues share Uxx (U01..U26).
    - Discontinuous singletons: old naming aa+index, e.g. W01, F02.
    """
    fragments = split_continuous_neighbor_fragments(neighbor_uids, chain_position_index)
    if len(fragments) > 26:
        raise ValueError(
            f"fragment_count_exceeds_26: discontinuous_fragments={len(fragments)}"
        )

    overrides = {}
    u_counter = 0
    single_counter = 0

    for fragment in fragments:
        if len(fragment) >= 2:
            u_counter += 1
            fragment_name = f"U{u_counter:02d}"
            for uid in fragment:
                overrides[uid] = fragment_name
        else:
            uid = fragment[0]
            residue = uid_to_residue.get(uid)
            if residue is None:
                continue
            aa1 = seq1(residue.get_resname()).upper()
            if aa1 not in STANDARD_AA:
                aa1 = "X"
            single_counter += 1
            overrides[uid] = f"{aa1}{single_counter:02d}"

    return overrides, len(fragments), fragments


def format_pdb_atom_line(atom, serial, record="ATOM", resname_override=None):
    if resname_override is not None:
        record = "HETATM"
    res = atom.get_parent()
    chain = res.get_parent()
    atom_name = atom.get_name().strip()
    altloc = atom.get_altloc() if atom.get_altloc() != " " else " "
    if resname_override is None:
        resname = res.get_resname().strip()[:3]
    else:
        resname = str(resname_override).strip()[:3]
    chain_id = chain.id
    _, resseq, icode = res.id
    x, y, z = atom.coord
    occ = atom.get_occupancy() if atom.get_occupancy() is not None else 1.00
    bfac = atom.get_bfactor() if atom.get_bfactor() is not None else 0.00
    element = (atom.element or atom_name[0]).strip().upper()[:2]
    if len(atom_name) < 4:
        atom_name_fmt = f" {atom_name:<3}"
    else:
        atom_name_fmt = atom_name[:4]
    return (
        f"{record:<6}{serial:>5d} {atom_name_fmt}{altloc:1}"
        f"{resname:>3s} {chain_id:1s}{int(resseq):>4d}{(icode or ' '):1s}   "
        f"{x:>8.3f}{y:>8.3f}{z:>8.3f}{occ:>6.2f}{bfac:>6.2f}          {element:>2s}"
    )


def process_one_file(file_name, grp_df, l_chain="L", cutoff=8.0, ori_source="l_chain_all_sidechain"):
    try:
        if ori_source not in VALID_ORI_SOURCES:
            raise ValueError(f"Unsupported ori_source: {ori_source}")

        pdb_stem = safe_file_stem(file_name)
        pdb_path = MINIMIZED_DIR / f"{pdb_stem}.pdb"
        if not pdb_path.exists():
            return {
                "file": file_name,
                "status": "missing_pdb",
                "message": str(pdb_path),
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_fragments": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, []

        structure = parser.get_structure(file_name, str(pdb_path))
        model = structure[0]

        if ORI_CHAIN_ID in {chain.id for chain in model}:
            return {
                "file": file_name,
                "status": "error",
                "message": f"ORI chain conflict: chain {ORI_CHAIN_ID} already exists",
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_fragments": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, []

        wt_series, pose_series = parse_mutant_series(grp_df["Mutant"])
        grp = grp_df.copy()
        grp["wt_aa"] = wt_series.values
        grp["pose_index"] = pose_series.values

        _, pose_to_meta = build_pose_index_map(model)
        mapping_rows = []
        target_uids = []

        for _, row in grp.iterrows():
            pose_idx = int(row["pose_index"])
            wt_aa = row["wt_aa"]
            mut = row["Mutant"]

            meta = pose_to_meta.get(pose_idx)
            if meta is None:
                mapping_rows.append({
                    "File": file_name,
                    "Mutant": mut,
                    "wt_aa": wt_aa,
                    "pose_index": pose_idx,
                    "mapped": False,
                    "reason": "pose_not_found",
                    "mapped_chain": "",
                    "mapped_resseq": np.nan,
                    "mapped_icode": "",
                    "mapped_resname1": "",
                    "wt_match": False,
                })
                continue

            mapped_chain = meta["chain"]
            mapped_resseq = meta["resseq"]
            mapped_icode = meta["icode"]
            mapped_resname1 = meta["resname1"]
            wt_match = wt_aa == mapped_resname1

            reason = "ok"
            if mapped_chain != l_chain:
                reason = "not_in_L_chain"
            elif not wt_match:
                reason = "wt_mismatch"
            else:
                target_uids.append((mapped_chain, mapped_resseq, mapped_icode))

            mapping_rows.append({
                "File": file_name,
                "Mutant": mut,
                "wt_aa": wt_aa,
                "pose_index": pose_idx,
                "mapped": True,
                "reason": reason,
                "mapped_chain": mapped_chain,
                "mapped_resseq": mapped_resseq,
                "mapped_icode": mapped_icode,
                "mapped_resname1": mapped_resname1,
                "wt_match": wt_match,
            })

        target_uids = sorted(set(target_uids), key=lambda x: (x[0], x[1], x[2]))
        if not target_uids:
            return {
                "file": file_name,
                "status": "no_valid_L_targets",
                "message": "No valid L-chain targets after pose mapping",
                "output_pdb": "",
                "n_l_targets": 0,
                "n_neighbors": 0,
                "n_fragments": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, mapping_rows

        backbone_atoms = get_backbone_atoms_of_chain(model, chain_id=l_chain)
        if not backbone_atoms:
            return {
                "file": file_name,
                "status": "no_L_backbone",
                "message": "L chain has no standard backbone atoms",
                "output_pdb": "",
                "n_l_targets": len(target_uids),
                "n_neighbors": 0,
                "n_fragments": 0,
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, mapping_rows

        uid_to_residue = {
            residue_uid(chain.id, residue): residue
            for chain in model
            for residue in chain
            if residue_is_standard_aa(residue)
        }
        chain_position_index = build_chain_position_index(model)

        neighbor_uids = []
        for chain in model:
            if chain.id == l_chain:
                continue
            for residue in chain:
                if not residue_is_standard_aa(residue):
                    continue
                dmin = min_distance_to_query_atoms(residue, backbone_atoms)
                if dmin < cutoff:
                    neighbor_uids.append((chain.id, residue.id[1], (residue.id[2] or " ").strip()))

        neighbor_uids = sorted(set(neighbor_uids), key=lambda x: (x[0], x[1], x[2]))

        try:
            protein_resname_overrides, n_fragments, _fragments = build_protein_resname_overrides(
                neighbor_uids, uid_to_residue, chain_position_index
            )
        except ValueError as exc:
            return {
                "file": file_name,
                "status": "error",
                "message": str(exc),
                "output_pdb": "",
                "n_l_targets": len(target_uids),
                "n_neighbors": len(neighbor_uids),
                "n_fragments": len(split_continuous_neighbor_fragments(neighbor_uids, chain_position_index)),
                "n_written_atoms": 0,
                "ori_chain": "",
                "ori_source": ori_source,
                "ori_x": np.nan,
                "ori_y": np.nan,
                "ori_z": np.nan,
            }, mapping_rows

        if ori_source == "l_chain_all_sidechain":
            ori_atoms = get_l_chain_all_sidechain_atoms(model, chain_id=l_chain)
        else:
            ori_atoms = []
            for uid in target_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                # L-chain requirement: only sidechain atoms of hotspot residues.
                ori_atoms.extend(sidechain_atoms(res))
        ori_coord = calculate_centroid_from_atoms(ori_atoms)

        HOTSPOT_OUT_DIR.mkdir(parents=True, exist_ok=True)
        out_path = HOTSPOT_OUT_DIR / f"{Path(str(file_name)).name}_hotspot.pdb"

        serial = 1
        written = 0
        with open(out_path, "w") as f:
            # L-chain keeps hotspot sidechain atoms only.
            for uid in target_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                for atom in sidechain_atoms(res):
                    f.write(format_pdb_atom_line(atom, serial, record="ATOM") + "\n")
                    serial += 1
                    written += 1

            # Non-L extracted residues: write full residue atoms as HETATM.
            for uid in neighbor_uids:
                res = uid_to_residue.get(uid)
                if res is None:
                    continue
                resname_override = protein_resname_overrides.get(uid)
                for atom in residue_all_atoms(res):
                    f.write(
                        format_pdb_atom_line(
                            atom, serial, record="ATOM", resname_override=resname_override
                        ) + "\n"
                    )
                    serial += 1
                    written += 1

            f.write(format_ori_hetatm_line(ori_coord, chain_id=ORI_CHAIN_ID) + "\n")
            f.write("END\n")

        status = "ok" if written > 0 else "empty_hotspot"
        message = "" if written > 0 else "No atoms written"
        return {
            "file": file_name,
            "status": status,
            "message": message,
            "output_pdb": str(out_path),
            "n_l_targets": len(target_uids),
            "n_neighbors": len(neighbor_uids),
            "n_fragments": n_fragments,
            "n_written_atoms": written,
            "ori_chain": ORI_CHAIN_ID,
            "ori_source": ori_source,
            "ori_x": ori_coord[0],
            "ori_y": ori_coord[1],
            "ori_z": ori_coord[2],
        }, mapping_rows
    except Exception as exc:
        return {
            "file": file_name,
            "status": "error",
            "message": f"{type(exc).__name__}: {exc}",
            "output_pdb": "",
            "n_l_targets": 0,
            "n_neighbors": 0,
            "n_fragments": 0,
            "n_written_atoms": 0,
            "ori_chain": "",
            "ori_source": ori_source,
            "ori_x": np.nan,
            "ori_y": np.nan,
            "ori_z": np.nan,
        }, []


df_debug_summary, df_debug_mapping = run_stage1_stage2_debug(
    smoke_n=3,
    run_full=True,
    l_chain="L",
    cutoff=8.0,
    ori_source="l_chain_all_sidechain",
    write_mapping_log=True,
)

display(df_debug_summary)
display(df_debug_mapping.head(20))

Total files in CSV: 148
Files to process now: 148
ORI source: l_chain_all_sidechain
[ok] ddg_1ddv_0012 | L_targets=1 neighbors=19 atoms=166 ORI=(12.254, 18.412, -0.591)
[ok] ddg_1eg4_0003 | L_targets=2 neighbors=25 atoms=224 ORI=(53.750, 16.599, 35.935)
[ok] ddg_1f47_0001 | L_targets=6 neighbors=19 atoms=179 ORI=(9.338, 11.238, 14.377)
[ok] ddg_1f8h_0003 | L_targets=2 neighbors=21 atoms=179 ORI=(3.895, -0.621, -1.155)
[ok] ddg_1j2x_0001 | L_targets=6 neighbors=21 atoms=194 ORI=(-0.946, -2.193, 9.972)
[ok] ddg_1jd5_0001 | L_targets=3 neighbors=30 atoms=266 ORI=(-0.708, 47.139, 12.938)
[ok] ddg_1jq8_0001 | L_targets=2 neighbors=31 atoms=264 ORI=(13.131, 21.543, 42.654)
[ok] ddg_1jw6_0019 | L_targets=2 neighbors=19 atoms=170 ORI=(12.546, 31.709, 25.323)
[ok] ddg_1l2z_0001 | L_targets=1 neighbors=17 atoms=166 ORI=(12.182, 0.460, 1.292)
[ok] ddg_1lb6_0004 | L_targets=3 neighbors=26 atoms=235 ORI=(12.313, 23.066, 10.739)
[ok] ddg_1mv0_0001 | L_targets=3 neighbors=30 atoms=273 ORI=(-0.969, -11.447, -14.319)
[ok] ddg_1nrl_0016 | L_targets=7 neighbors=21 atoms=200 ORI=(1.690, 12.045, 18.573)
[ok] ddg_1nvq_0018 | L_targets=2 neighbors=24 atoms=217 ORI=(13.931, 4.008, 32.446)
[ok] ddg_1o0p_0001 | L_targets=6 neighbors=21 atoms=209 ORI=(9.415, -3.344, 7.092)
[ok] ddg_1p7v_0014 | L_targets=1 neighbors=44 atoms=321 ORI=(48.306, 44.852, 39.380)
[ok] ddg_1r17_0004 | L_targets=3 neighbors=63 atoms=520 ORI=(51.203, 13.274, 90.894)
[ok] ddg_1rxz_0001 | L_targets=5 neighbors=30 atoms=271 ORI=(78.673, 26.314, 14.538)
[ok] ddg_1t74_0006 | L_targets=4 neighbors=16 atoms=160 ORI=(38.232, -24.365, 54.164)
[ok] ddg_1v1t_0009 | L_targets=3 neighbors=26 atoms=209 ORI=(8.227, -19.195, 40.319)
[ok] ddg_1w80_0013 | L_targets=3 neighbors=21 atoms=187 ORI=(25.371, -15.212, -5.049)
[ok] ddg_1yfn_0001 | L_targets=7 neighbors=34 atoms=310 ORI=(30.788, -18.168, 7.287)
[ok] ddg_1ywi_0001 | L_targets=1 neighbors=13 atoms=122 ORI=(1.266, 7.602, 0.415)
[ok] ddg_1ywo_0001 | L_targets=1 neighbors=15 atoms=141 ORI=(19.491, 2.467, 25.868)
[ok] ddg_1yy6_0001 | L_targets=1 neighbors=25 atoms=218 ORI=(34.731, -15.809, -8.388)
[ok] ddg_2aq9_0005 | L_targets=3 neighbors=21 atoms=179 ORI=(51.353, 71.420, 65.326)
[ok] ddg_2c3i_0007 | L_targets=3 neighbors=26 atoms=235 ORI=(21.389, 59.438, -12.912)
[ok] ddg_2cch_0010 | L_targets=6 neighbors=29 atoms=285 ORI=(4.982, 14.459, 49.789)
[ok] ddg_2cny_0001 | L_targets=9 neighbors=53 atoms=447 ORI=(30.905, -13.634, 45.015)
[ok] ddg_2e4h_0001 | L_targets=2 neighbors=32 atoms=250 ORI=(-0.313, 3.696, 15.226)
[ok] ddg_2fgr_0005 | L_targets=1 neighbors=13 atoms=109 ORI=(4.479, 58.568, 21.550)
[ok] ddg_2fka_0001 | L_targets=4 neighbors=19 atoms=163 ORI=(42.681, -85.665, -76.304)
[ok] ddg_2hpl_0002 | L_targets=2 neighbors=20 atoms=178 ORI=(49.315, 51.511, 21.337)
[ok] ddg_2ht9_0012 | L_targets=5 neighbors=9 atoms=105 ORI=(-24.072, 56.019, -1.260)
[ok] ddg_2i94_0008 | L_targets=4 neighbors=32 atoms=302 ORI=(4.689, 13.958, -44.329)
[ok] ddg_2ivz_0009 | L_targets=3 neighbors=38 atoms=327 ORI=(16.917, 16.822, 57.636)
[ok] ddg_2jnw_0001 | L_targets=2 neighbors=28 atoms=254 ORI=(-12.514, 7.721, -12.234)
[ok] ddg_2jqk_0001 | L_targets=2 neighbors=18 atoms=156 ORI=(8.369, -4.466, 5.036)
[ok] ddg_2ka9_0008 | L_targets=3 neighbors=26 atoms=201 ORI=(-14.313, -14.215, 16.448)
[ok] ddg_2kbr_0001 | L_targets=6 neighbors=26 atoms=259 ORI=(-9.295, 0.207, 6.375)
[ok] ddg_2ke1_0001 | L_targets=6 neighbors=30 atoms=266 ORI=(11.288, -0.337, 2.138)
[ok] ddg_2khh_0001 | L_targets=4 neighbors=24 atoms=209 ORI=(-11.340, -44.716, 14.315)
[ok] ddg_2koh_0003 | L_targets=4 neighbors=33 atoms=253 ORI=(0.980, -4.739, 20.857)
[ok] ddg_2las_0006 | L_targets=3 neighbors=20 atoms=186 ORI=(6.920, 7.371, 3.767)
[ok] ddg_2lsi_0002 | L_targets=6 neighbors=19 atoms=190 ORI=(14.102, 6.773, 0.548)
[ok] ddg_2m0v_0001 | L_targets=2 neighbors=28 atoms=227 ORI=(2.609, 27.053, 4.432)
[ok] ddg_2nnu_0016 | L_targets=7 neighbors=19 atoms=193 ORI=(32.863, 6.075, 30.385)
[ok] ddg_2o9v_0001 | L_targets=1 neighbors=17 atoms=155 ORI=(26.688, -5.685, -16.188)
[ok] ddg_2p1o_0010 | L_targets=3 neighbors=27 atoms=251 ORI=(14.033, -102.927, -28.981)
[ok] ddg_2qos_0017 | L_targets=5 neighbors=44 atoms=397 ORI=(35.729, 35.070, 50.765)
[ok] ddg_2r7g_0020 | L_targets=6 neighbors=29 atoms=274 ORI=(-6.336, -4.774, 14.363)
[ok] ddg_2rol_0001 | L_targets=2 neighbors=17 atoms=160 ORI=(19.276, 21.231, 11.657)
[ok] ddg_2vzg_0004 | L_targets=6 neighbors=19 atoms=184 ORI=(-18.773, -12.690, 18.348)
[ok] ddg_2xcb_0019 | L_targets=3 neighbors=28 atoms=266 ORI=(-15.377, 37.740, -14.658)
[ok] ddg_2xpn_0005 | L_targets=5 neighbors=29 atoms=258 ORI=(-20.867, 23.512, -2.301)
[ok] ddg_2xrw_0003 | L_targets=5 neighbors=21 atoms=204 ORI=(-9.887, 4.227, 24.532)
[ok] ddg_2ymt_0001 | L_targets=3 neighbors=19 atoms=177 ORI=(-11.119, 6.457, 10.918)
[ok] ddg_3agy_0002 | L_targets=1 neighbors=22 atoms=187 ORI=(3.392, 5.961, 93.493)
[ok] ddg_3bej_0005 | L_targets=5 neighbors=19 atoms=187 ORI=(28.633, 9.184, 0.526)
[ok] ddg_3bqo_0001 | L_targets=8 neighbors=38 atoms=362 ORI=(46.848, 24.427, -18.766)
[ok] ddg_3emh_0003 | L_targets=2 neighbors=32 atoms=260 ORI=(-15.299, -29.422, -5.533)
[ok] ddg_3emw_0013 | L_targets=4 neighbors=20 atoms=179 ORI=(11.078, 30.419, 61.113)
[ok] ddg_3et3_0010 | L_targets=8 neighbors=25 atoms=236 ORI=(52.299, 29.313, 78.550)
[ok] ddg_3fp2_0003 | L_targets=3 neighbors=26 atoms=217 ORI=(-1.765, 20.343, 53.833)
[ok] ddg_3g2s_0001 | L_targets=5 neighbors=24 atoms=221 ORI=(15.181, 3.133, -37.543)
[ok] ddg_3h1z_0013 | L_targets=6 neighbors=29 atoms=271 ORI=(-16.856, -9.509, -40.754)
[ok] ddg_3i5r_0001 | L_targets=3 neighbors=13 atoms=131 ORI=(2.332, 25.221, 18.405)
[ok] ddg_3pe4_0009 | L_targets=3 neighbors=48 atoms=404 ORI=(-12.494, 29.760, 4.742)
[ok] ddg_3plu_0006 | L_targets=6 neighbors=16 atoms=160 ORI=(3.691, -14.692, -4.486)
[ok] ddg_3r42_0018 | L_targets=2 neighbors=20 atoms=179 ORI=(7.259, 15.868, -5.873)
[ok] ddg_3s9c_0004 | L_targets=5 neighbors=35 atoms=290 ORI=(-3.040, 44.360, 3.321)
[ok] ddg_3shb_0006 | L_targets=2 neighbors=21 atoms=179 ORI=(-12.768, 9.962, 13.076)
[ok] ddg_3tiw_0001 | L_targets=5 neighbors=21 atoms=201 ORI=(14.255, -8.348, -20.442)
[ok] ddg_3v2o_0013 | L_targets=2 neighbors=28 atoms=232 ORI=(-4.393, 3.736, 1.649)
[ok] ddg_4a2a_0013 | L_targets=7 neighbors=22 atoms=219 ORI=(-21.144, -7.047, 61.549)
[ok] ddg_4c5a_0012 | L_targets=4 neighbors=10 atoms=104 ORI=(-7.873, 35.880, 33.563)
[ok] ddg_4dg3_0002 | L_targets=6 neighbors=43 atoms=402 ORI=(-14.559, -1.036, 8.962)
[ok] ddg_4ep2_0009 | L_targets=3 neighbors=56 atoms=419 ORI=(20.663, 31.499, 12.939)
[ok] ddg_4fii_0001 | L_targets=4 neighbors=27 atoms=243 ORI=(23.431, -22.862, -4.762)
[ok] ddg_4gq6_0004 | L_targets=3 neighbors=48 atoms=408 ORI=(-8.292, 14.754, 6.888)
[ok] ddg_4hdq_0008 | L_targets=4 neighbors=29 atoms=274 ORI=(29.303, 25.092, 16.964)
[error] ddg_4hom_0010 | L_targets=5 neighbors=74 atoms=0
[ok] ddg_4iga_0001 | L_targets=9 neighbors=21 atoms=201 ORI=(10.624, -28.488, -0.347)
[ok] ddg_4j2c_0001 | L_targets=7 neighbors=22 atoms=222 ORI=(-7.351, 16.974, 20.616)
[ok] ddg_4j8b_0010 | L_targets=5 neighbors=22 atoms=225 ORI=(-31.458, -20.093, 8.222)
[ok] ddg_4lk9_0013 | L_targets=4 neighbors=34 atoms=296 ORI=(8.188, 29.581, 29.511)
[ok] ddg_4lzf_0006 | L_targets=2 neighbors=23 atoms=208 ORI=(5.826, 10.446, -6.829)
[ok] ddg_4m5s_0013 | L_targets=3 neighbors=24 atoms=190 ORI=(10.101, 12.186, 20.033)
[ok] ddg_4mvi_0002 | L_targets=7 neighbors=55 atoms=484 ORI=(-27.015, -1.202, -2.615)
[ok] ddg_4nuu_0006 | L_targets=6 neighbors=24 atoms=235 ORI=(47.166, -44.753, 95.481)
[ok] ddg_4nxr_0008 | L_targets=5 neighbors=29 atoms=263 ORI=(1.253, 12.248, 3.030)
[ok] ddg_4ny3_0016 | L_targets=3 neighbors=18 atoms=166 ORI=(16.201, 5.509, 13.677)
[ok] ddg_4odk_0006 | L_targets=2 neighbors=21 atoms=185 ORI=(-9.147, 11.325, 9.257)
[ok] ddg_4ouc_0018 | L_targets=3 neighbors=34 atoms=299 ORI=(35.645, 54.144, 9.758)
[ok] ddg_4oyk_0002 | L_targets=4 neighbors=24 atoms=238 ORI=(7.651, -6.600, -0.307)
[ok] ddg_4pd1_0009 | L_targets=4 neighbors=29 atoms=259 ORI=(-30.100, -10.447, 8.352)
[error] ddg_4pge_0001 | L_targets=3 neighbors=58 atoms=0
[ok] ddg_4qbr_0001 | L_targets=3 neighbors=33 atoms=275 ORI=(26.399, -32.638, 9.742)
[ok] ddg_4r5i_0008 | L_targets=3 neighbors=33 atoms=264 ORI=(-18.681, -22.112, -29.775)
[ok] ddg_4txr_0001 | L_targets=6 neighbors=19 atoms=194 ORI=(4.192, -14.084, -2.154)
[ok] ddg_4u0c_0001 | L_targets=2 neighbors=23 atoms=186 ORI=(-15.772, 75.748, 1.327)
[ok] ddg_4uqy_0001 | L_targets=7 neighbors=36 atoms=321 ORI=(14.261, -18.704, -33.635)
[ok] ddg_4x2h_0011 | L_targets=2 neighbors=30 atoms=236 ORI=(-76.915, 210.200, 82.037)
[ok] ddg_4x3o_0007 | L_targets=1 neighbors=27 atoms=235 ORI=(8.328, -3.712, 7.837)
[ok] ddg_4xc2_0001 | L_targets=5 neighbors=33 atoms=317 ORI=(16.280, 4.171, -0.331)
[ok] ddg_4xek_0003 | L_targets=6 neighbors=23 atoms=207 ORI=(-23.859, -1.002, 3.081)
[ok] ddg_4z2o_0018 | L_targets=4 neighbors=28 atoms=220 ORI=(-6.343, 3.498, -5.355)
[ok] ddg_5bs2_0004 | L_targets=4 neighbors=13 atoms=135 ORI=(-14.163, 14.731, 0.787)
[ok] ddg_5crw_0003 | L_targets=2 neighbors=25 atoms=196 ORI=(5.450, -5.805, 6.366)
[ok] ddg_5d94_0004 | L_targets=6 neighbors=31 atoms=300 ORI=(14.939, 1.924, 16.790)
[ok] ddg_5dai_0003 | L_targets=6 neighbors=25 atoms=233 ORI=(5.487, 36.308, -0.050)
[ok] ddg_5e33_0004 | L_targets=3 neighbors=47 atoms=419 ORI=(138.196, -21.905, 85.176)
[ok] ddg_5efi_0017 | L_targets=5 neighbors=36 atoms=312 ORI=(32.581, -5.340, 42.908)
[ok] ddg_5ei3_0001 | L_targets=7 neighbors=25 atoms=249 ORI=(1.161, -13.627, -35.958)
[ok] ddg_5fml_0008 | L_targets=8 neighbors=29 atoms=274 ORI=(50.641, 20.792, 38.941)
[ok] ddg_5fpx_0011 | L_targets=3 neighbors=37 atoms=310 ORI=(17.810, 0.412, -4.327)
[ok] ddg_5fv6_0010 | L_targets=2 neighbors=15 atoms=131 ORI=(12.026, 69.178, 3.192)
[ok] ddg_5ggp_0009 | L_targets=1 neighbors=9 atoms=93 ORI=(50.832, 2.997, 12.545)
[ok] ddg_5gu4_0003 | L_targets=3 neighbors=20 atoms=180 ORI=(-14.516, 7.498, 22.064)
[ok] ddg_5huw_0002 | L_targets=2 neighbors=39 atoms=328 ORI=(-2.465, 5.914, -8.107)
[ok] ddg_5i7z_0002 | L_targets=4 neighbors=27 atoms=235 ORI=(17.964, 32.396, -2.848)
[ok] ddg_5j3q_0014 | L_targets=4 neighbors=28 atoms=274 ORI=(-13.536, -20.433, 2.718)
[ok] ddg_5lyn_0001 | L_targets=3 neighbors=31 atoms=263 ORI=(4.931, 6.368, -34.683)
[ok] ddg_5m5r_0014 | L_targets=4 neighbors=29 atoms=238 ORI=(-14.038, -0.605, -15.405)
[ok] ddg_5n22_0001 | L_targets=4 neighbors=29 atoms=259 ORI=(79.853, 41.877, 50.836)
[ok] ddg_5n85_0006 | L_targets=6 neighbors=25 atoms=238 ORI=(5.664, 12.991, -2.696)
[ok] ddg_5njc_0015 | L_targets=1 neighbors=38 atoms=296 ORI=(30.413, 63.947, 50.787)
[ok] ddg_5nqv_0006 | L_targets=3 neighbors=32 atoms=285 ORI=(-30.529, -42.983, 45.386)
[ok] ddg_5oj5_0004 | L_targets=2 neighbors=14 atoms=126 ORI=(27.634, 4.816, -45.172)
[ok] ddg_5onp_0001 | L_targets=2 neighbors=31 atoms=278 ORI=(9.396, 40.641, -2.361)
[ok] ddg_5t0k_0001 | L_targets=3 neighbors=39 atoms=361 ORI=(-71.377, -12.934, 13.010)
[ok] ddg_5tgi_0013 | L_targets=7 neighbors=26 atoms=249 ORI=(4.898, 27.747, -16.944)
[ok] ddg_5v3r_0007 | L_targets=4 neighbors=23 atoms=205 ORI=(30.634, 40.377, 1.803)
[ok] ddg_5wfv_0011 | L_targets=3 neighbors=37 atoms=303 ORI=(-43.855, -9.791, 64.710)
[ok] ddg_5wyi_0011 | L_targets=3 neighbors=16 atoms=157 ORI=(76.117, 3.158, -26.639)
[ok] ddg_5xhz_0001 | L_targets=4 neighbors=19 atoms=189 ORI=(-15.241, 0.830, -1.243)
[ok] ddg_5xxq_0019 | L_targets=6 neighbors=26 atoms=253 ORI=(83.351, 26.319, 232.574)
[ok] ddg_5yay_0001 | L_targets=8 neighbors=42 atoms=358 ORI=(12.904, -10.191, 25.629)
[ok] ddg_6b27_0004 | L_targets=2 neighbors=21 atoms=208 ORI=(15.939, 49.798, 22.106)
[ok] ddg_6co4_0017 | L_targets=2 neighbors=32 atoms=277 ORI=(49.451, -4.948, 8.587)
[ok] ddg_6dei_0014 | L_targets=6 neighbors=25 atoms=245 ORI=(0.914, -3.247, 27.310)
[ok] ddg_6e5x_0012 | L_targets=2 neighbors=25 atoms=214 ORI=(9.234, 2.669, 15.816)
[ok] ddg_6ej7_0007 | L_targets=1 neighbors=42 atoms=358 ORI=(-0.371, 21.433, 72.865)
[ok] ddg_6f0w_0007 | L_targets=6 neighbors=43 atoms=394 ORI=(-13.836, 6.231, -14.360)
[ok] ddg_6f0y_0011 | L_targets=5 neighbors=24 atoms=216 ORI=(-10.440, -6.355, -9.018)
[ok] ddg_6f6d_0002 | L_targets=6 neighbors=68 atoms=574 ORI=(96.271, -19.332, 22.407)
[ok] ddg_6fbk_0001 | L_targets=5 neighbors=18 atoms=179 ORI=(37.879, 33.149, 4.399)
[ok] ddg_6g5g_0004 | L_targets=6 neighbors=27 atoms=273 ORI=(20.902, -4.031, 9.426)
[ok] ddg_6h7b_0001 | L_targets=5 neighbors=26 atoms=235 ORI=(6.286, -32.448, -7.268)

Mapping log saved: /home/junjiechen/1_work/250401-Dpepalign/Benchmark/RFdiffusion2/rfd2_hotspots/pose_mapping_debug.csv

,file,status,message,output_pdb,n_l_targets,n_neighbors,n_fragments,n_written_atoms,ori_chain,ori_source,ori_x,ori_y,ori_z
0,ddg_1ddv_0012,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,1,19,7,166,Z,l_chain_all_sidechain,12.253952,18.412381,-0.591190
1,ddg_1eg4_0003,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,2,25,7,224,Z,l_chain_all_sidechain,53.749833,16.598593,35.934945
2,ddg_1f47_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,19,12,179,Z,l_chain_all_sidechain,9.338446,11.238014,14.376946
3,ddg_1f8h_0003,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,2,21,7,179,Z,l_chain_all_sidechain,3.895462,-0.620769,-1.154577
4,ddg_1j2x_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,21,8,194,Z,l_chain_all_sidechain,-0.945857,-2.192730,9.971873
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,ddg_6f0y_0011,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,24,3,216,Z,l_chain_all_sidechain,-10.440464,-6.354768,-9.017911
144,ddg_6f6d_0002,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,68,21,574,Z,l_chain_all_sidechain,96.270732,-19.331857,22.406536
145,ddg_6fbk_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,18,6,179,Z,l_chain_all_sidechain,37.878873,33.148841,4.399222
146,ddg_6g5g_0004,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,6,27,11,273,Z,l_chain_all_sidechain,20.902349,-4.031205,9.425940
147,ddg_6h7b_0001,ok,,/home/junjiechen/1_work/250401-Dpepalign/Bench...,5,26,8,235,Z,l_chain_all_sidechain,6.285840,-32.448020,-7.268360

,File,Mutant,wt_aa,pose_index,mapped,reason,mapped_chain,mapped_resseq,mapped_icode,mapped_resname1,wt_match
0,ddg_1ddv_0012,F110A,F,110,True,ok,L,1006,,F,True
1,ddg_1eg4_0003,Y271A,Y,271,True,ok,L,12,,Y,True
2,ddg_1eg4_0003,R266A,R,266,True,ok,L,7,,R,True
3,ddg_1f47_0001,F155A,F,155,True,ok,L,11,,F,True
4,ddg_1f47_0001,Y149A,Y,149,True,ok,L,5,,Y,True
5,ddg_1f47_0001,L156A,L,156,True,ok,L,12,,L,True
6,ddg_1f47_0001,I152A,I,152,True,ok,L,8,,I,True
7,ddg_1f47_0001,L150A,L,150,True,ok,L,6,,L,True
8,ddg_1f47_0001,D148A,D,148,True,ok,L,4,,D,True
9,ddg_1f8h_0003,F100A,F,100,True,ok,L,111,,F,True
10,ddg_1f8h_0003,R101A,R,101,True,ok,L,112,,R,True
11,ddg_1j2x_0001,L80A,L,80,True,ok,L,953,,L,True
12,ddg_1j2x_0001,L84A,L,84,True,ok,L,957,,L,True
13,ddg_1j2x_0001,M76A,M,76,True,ok,L,949,,M,True
14,ddg_1j2x_0001,D74A,D,74,True,ok,L,947,,D,True
15,ddg_1j2x_0001,L87A,L,87,True,ok,L,960,,L,True
16,ddg_1j2x_0001,M88A,M,88,True,ok,L,961,,M,True
17,ddg_1jd5_0001,Y109A,Y,109,True,ok,L,4,,Y,True
18,ddg_1jd5_0001,I111A,I,111,True,ok,L,6,,I,True
19,ddg_1jd5_0001,F110A,F,110,True,ok,L,5,,F,True